apiVersion: apps/v1
kind: Deployment  ///object
metadata:
  name: dep-Myapp
  labels:
    app: Myapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: Myapp
  template:
    metadata:
      labels:
        app: Myapp
    spec:
      containers:
      - name: container-Myapp
        image: ayswarya430/app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: Myapp-svc
  labels:
    app: Myapp
spec:
  #type: LoadBalancer
  #type: NodePort
  ports:
  - port: 80
  #nodePort: 30001
  selector:
    app: Myapp

----------------



